In [178]:

import numpy as np

In [179]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a2

array([ 6,  7,  8,  9, 10])

In [180]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [181]:
a1-a2

array([-5, -5, -5, -5, -5])

In [182]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [183]:
l=[10,20,30,40,50]
arr=np.array(l)

In [184]:
arr+10


array([20, 30, 40, 50, 60])

In [185]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [186]:
arr2+10



array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [187]:
arr2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [188]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [189]:
slice =a[:5]
slice=slice**2
slice

array([ 1,  4,  9, 16, 25])

In [190]:
a
b=a.copy

In [191]:
b

<function ndarray.copy(order='C')>

In [192]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [193]:
m=np.array([[1,2],[3,4]])
n=np.array([[5,6],[7,8]])

In [194]:
m

array([[1, 2],
       [3, 4]])

In [195]:
n 

array([[5, 6],
       [7, 8]])

matrix multiplaction

In [196]:
m@n

array([[19, 22],
       [43, 50]])

In [197]:
n@m

array([[23, 34],
       [31, 46]])

In [198]:
np.dot(m,n)

array([[19, 22],
       [43, 50]])

transpose


In [199]:
m.T

array([[1, 3],
       [2, 4]])

In [200]:
n.T


array([[5, 7],
       [6, 8]])

advancr array manuplations

stacking array

In [201]:
np.vstack((m,n))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [202]:
np.hstack((m,n))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [203]:
np.column_stack((m,n))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

splitting array

In [204]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [205]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [206]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [207]:
for i in a:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


numpy exersise

In [208]:
import numpy as np

In [209]:
s=np.array([
    [5,3,4,6,7,8,9,1,2] ,
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
    ])

In [210]:
for i in range(0,9,3):
   for j in range(0,9,3):
      n=s[i:i+3,j:j+3]
      print(n.sum())
        


45
45
45
45
45
45
45
45
45


In [211]:
s.sum()

np.int64(405)

In [212]:
b=np.sum(s,axis=1)
for i in b:
    if i!=45:
        print("sudoku is not valid")
        break
    else:
        print("for rows it is valid")


for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid


In [213]:
c=np.sum(s,axis=1)
for i in c:
    if i!=45:
        print("sudoku is not valid")
        break
    else:
        print("for colomns it is valid")


for colomns it is valid
for colomns it is valid
for colomns it is valid
for colomns it is valid
for colomns it is valid
for colomns it is valid
for colomns it is valid
for colomns it is valid
for colomns it is valid


In [214]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [215]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [216]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [217]:
import numpy as np

In [218]:
data=np.array([

    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85],

])

In [219]:
data.shape

(5, 3)

In [220]:
np.mean(data[:,0])

np.float64(18.4)

In [221]:
data[:,1]

array([85, 92, 76, 65, 90])

In [222]:
data[:,2]


array([78, 88, 95, 70, 85])

In [223]:
np.max(data[:,2])

np.int64(95)

In [224]:
data[data[:,2]>90]


array([[17, 76, 95]])

In [225]:
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [226]:
len(data[data[:,0]<19])


3

In [227]:
np.mean (data[:,1:])

np.float64(84.9)

In [228]:
data[(data[:,1]>=80) & (data[:,2]>=80)]
    

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [229]:
data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [230]:
data[:,2] [data[:,2]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])