import numpy as np

import numpy as np

In [85]:
import numpy as np


In [86]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

indxing

In [87]:
arr[9]

np.int64(20)

slising

In [88]:
arr[1:6:2]

array([12, 14, 16])

In [89]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [90]:
arr[0:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [91]:
arr[3::2]

array([14, 16, 18, 20])

numpy indxing and slising of mattrix

In [92]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

rows printing

In [93]:
slice=arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [94]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

colomun

In [95]:
arr[0,0]

np.int64(1)

In [96]:
arr[3,4]

np.int64(20)

In [97]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

BOOLEAN INDXING

In [98]:
arr=np.arange(11,21)
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [99]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [100]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

array oprations
