In [1]:
import numpy as np

In [ ]:
rr=np.array([1,2,3,4,5])
rr

array([1, 2, 3, 4, 5])

In [3]:
a=[1,2,3,5.6,"anurag"]
a

[1, 2, 3, 5.6, 'anurag']

In [4]:
np.array(a)

array(['1', '2', '3', '5.6', 'anurag'], dtype='<U32')

In [5]:
m=[[1,3,4],[5,6,7],[8,9,0]]
m

[[1, 3, 4], [5, 6, 7], [8, 9, 0]]

In [6]:
m=[[1,2,3],[5,6,7],[8,9,0]]
arr= np.array(m)
m

[[1, 2, 3], [5, 6, 7], [8, 9, 0]]

In [7]:
np.array(m)


array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [8]:
arr=np.arange(1,11,3)
arr


array([ 1,  4,  7, 10])

In [9]:
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
arr=np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr=np.linspace(0,1,1)
arr

array([0., 2.])

In [12]:
np.random.rand(1)

array([0.19449773])

In [13]:
arr=np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.random.randint(10,20,10)

array([19, 19, 16, 14, 17, 12, 13, 15, 13, 11], dtype=int32)

In [18]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.shape

(3, 3)

In [20]:
arr.size

9

In [21]:
arr.dtype

dtype('int64')

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr.min()

np.int64(1)

In [25]:
arr.max()

np.int64(9)

In [26]:
arr.sum()

np.int64(45)

In [27]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [29]:
np.sum(arr,axis=1)


array([ 6, 15, 24])

In [30]:
arr.mean()

np.float64(5.0)

In [31]:
arr.std()

np.float64(2.581988897471611)

In [32]:
arr.argmax()

np.int64(8)

In [33]:
arr.argmin()    

np.int64(0)

In [35]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [36]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [37]:
arr.reshape(6,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
import numpy as np
